version: "3.9"

services:
  nginx:
    image: nginx:1.24.0
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always
    depends_on:
      - mariadb
      - api
    
  mariadb:
    image: mariadb:11.3.2
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"

  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    env_file:
      - .env
    volumes: 
      - ./api/prisma:/usr/src/app/prisma
      - ./api/src/public/documents:/usr/src/app/src/public/documents
    depends_on:
      - mariadb
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
     - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
    
volumes:
  grafana-storage: {}
  data:
